### ISSUE TITLE
VFP2C32 for VFP Advanced 64

### ISSUE THREAD

**Issue by CHamlinPNP** [ChristianEhlscheid/vfp2c32#12]
Has anyone taken the time to recompile VFP2C32 into a x64 FLL so that VFP Advanced x64 can use the classes?

**Comment by jhernancanom** [comment]
Yes.
I can show you something.

**Comment by ChristianEhlscheid** [comment]
I've tried to convert the library a while ago, but got stuck because it's really complicated.
You just can't recompile to 64 bit and then everything is just fine,
There are functions in the library (CreateCallbackfunc, BindEventsEx) that emit 32 bit assembly instructions at runtime,
one would have to write an entire 64 bit runtime alternative, that's hundreds of small functions, the calling conventions (how parameters are passed on the stack) is totally different etc. It's not a small task, probably takes 1-2 months fulltime.
I don't intend to invest that amount of time, may i'll release a striped down 64 bit version of the fll that only contains the functions that are easily portable.
