### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by GerhardSc** [ChristianEhlscheid/vfp2c32#3]
Hello Christian,

I added VFP2C32.FLL and VFP2C.H to my project according to the help. When I try to compile I get 
  Unable to find Unknown INITVFP2C32.
Can you help me here?

TIA
Gerhard Schmidbauer

**Comment by ChristianEhlscheid** [comment]
Hello,

the function was removed from the library some time ago, it's no longer neccessary, since all functions load eventual dependencies (external dll's) on demand now. Just search your codebase and remove the function call.
Some 3rd party libraries that depend on VFP2C32 might also call the function and were not updated since the breaking change.

**Comment by GerhardSc** [comment]
Hello Christian,

Thank you for the very fast response!
