### ISSUE TITLE
recursive ADirEx

### ISSUE THREAD

**Issue by myearwood1** [ChristianEhlscheid/vfp2c32#8]
Can you change ADirEx to recurse subfolders please?

**Comment by myearwood1** [comment]
This was my request and it was not delivered to my wishes. I posted a new program done in FoxPro that anyone can use, and also made implementing ADirEx easier.

**Comment by ChristianEhlscheid** [comment]
Hello,
the newest version has an recursive option for AdirEx.
You might want to check it out.
If this does not fit your purposes please specify exactly what is missing and I might alter it.
I don't intent to develop this library further, I don't use FoxPro anymore and have 
no more motivation to work on it.
From now on there will only be bugfixes and these also only if they are relativly quick and easy to do.

**Comment by myearwood1** [comment]
You failed to deliver an recursive dir function which has been part of DOS
for for many years. I asked for the ability to be added and it was done
poorly. As you yourself say no one is upgrading this library so I showed
how professional Fox people can use what you donated without having to code
in C.

Is that a problem for you?

**Comment by ChristianEhlscheid** [comment]
Hello,
I asked for a specific bug report, just stating that "it was done poorly" doesn't tell me anything other than your not satisfied
with the current functionality.
If you file a bug report I have a look into it, otherwise I just leave it as it is, since for me it's working as intended and specified in the help file.

**Comment by myearwood1** [comment]
When I asked for it to be done, where were you?

I do not trust the person who made the change as he did not do as requested
without fighting.

I do not care if that feature works or not. It did not work when I last
wasted my time to check.

Adirex works for me as it was. I have more trust in Foxcroft source code
freely given that is easily implemented and easily maintained.

**Comment by ChristianEhlscheid** [comment]
I was not able to respond in the past cause of my personal situation at that time.

I did not fight, I just ignored the request in the past cause it was too much work,
but I did come back to it and extended AdirEx, which was a few weeks of work in my spare time.

The sourcecode is open source and everyone can have a look at it, I cannot be more transparent than that.
We will probably not come to some constructive argument, if you prove there's a bug in the code I will fix it, otherwise I consider this issue closed.

**Comment by myearwood1** [comment]
How can I add my example to your documentation? It is easier to use your
library the way I showed than the other examples.

**Comment by EnsignRho** [comment]
Fork the repository to your own account, add your cheese to your own copy, then create a pull request here so others can see your work exists (even if they come here).

**Comment by myearwood1** [comment]
RUDE.

**Comment by EnsignRho** [comment]
Changed from "cheese" to "content."  But, that is the process to get your offering out there (even on the original author's repository) if it won't be accepted by the original author.  Others can see the closed pull requests and find your work.

**Comment by myearwood1** [comment]
Regardless. RUDE is the default position of far too many.

I saw the other post that you, a supposedly religious person wrote and
deleted.

I inherited a terribly built app, like so many, and am having to struggle
because of all the lack of foresight around me.

Your comments are dismissed because unlike my contributions they are not a
teaching moment.

**Comment by EnsignRho** [comment]
This is the last time I will ever communicate with you, Mike.  Your negativity toward everyone is well known in the various forums.  I worked very hard to get that code to your satisfaction.  Nothing is ever good enough because of your negative attitude.

Good bye, Mike.  I hope you find joy in your life.

**Comment by myearwood1** [comment]
You refused to deliver it to my satisfaction until another convinced you. I
stand up against rude, disrespectful people.

I will be grateful not to hear from such.
